/// REGISTER
POST http://localhost:8080/users/register
Content-Type: application/json

{
    "Name": "Ben",
    "Email": "ben@gmail.com",
    "Password": "12345"
}

// LOGIN
###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "Email": "ben@gmail.com",
    "Password": "12345"
}

// PROFILE
###
GET http://localhost:8080/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJlbWFpbCI6ImJlbkBnbWFpbC5jb20iLCJleHAiOjE3Njc4MDQ3NTgsImlhdCI6MTc2NzgwMzg1OH0.P3cC3C6Lf6Um2mx32MQdHMca0MlR9OIlnmgPUQ4umnQ

/// REFRESH TOKEN
###
POST http://localhost:8080/auth/refresh 

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3Njg0MDc3NjgsImlhdCI6MTc2NzgwMjk2OH0.O3_GkFWY3NvD3ScLILuqCpRF-h9Q78VEaCKVOBMb90g"
}