/// REGISTER
POST http://localhost:8080/users/register
Content-Type: application/json

{
    "Name": "Joy",
    "Email": "joy@gmail.com",
    "Password": "12345"
}

// LOGIN
###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "Email": "joy@gmail.com",
    "Password": "12345"
}

// PROFILE
###
GET http://localhost:8080/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjozLCJlbWFpbCI6ImpveUBnbWFpbC5jb20iLCJleHAiOjE3NjYxNTY4NjAsImlhdCI6MTc2NjE1NTk2MH0.SRjtfTwZz6KIP05LFBvm3mEfCJcYyR0DGRYL8k1_KwA

/// REFRESH TOKEN
###
POST http://localhost:8080/auth/refresh